# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d978d81cf4bdc8c40149a0e287acfbab47d0a044781dc10f9b9a5ce03d90a0fbf56077b7827cf7bf624831745cb8091b4b4c58034b38afea1a4f26008351b945

test:
  secret_key_base: 77191fec797dea06dfb03f79cfbae8dcea58fb45a7ad2daeecfd2ab51c05afe608b3fee66618470348adc92833876df25afb56932c22bcd4bb36d8947d1417a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
